version: '3.2'

services:

  traefik:
    image: traefik:latest
    ports:
      - 80:80
      - 8080:8080
    command: traefik --docker --docker.swarmMode --docker.watch --docker.network=traefik_traefik-net --api
    #  --docker.trace --accessLog -l DEBUG 
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-net
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik-net
    deploy:
      labels:
        traefik.frontend.rule: "Host:portainer.example.com"
        traefik.backend: "portainer"
        traefik.port: "9000"
        traefik.enable: "true"
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  traefik-net:
    driver: overlay
    attachable: true
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
